name: Update badges

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          CREDLY_USER: hobrien@alumni.cmu.edu
